sleep(3)
Print('Hello')
sleep(1)
print('I am a program that is purely made for testing with Python')
sleep(2)
print('I hope i am helpfull to you in a good way')
sleep(2)
print('And i hope someguy has coded in some stuff in here')
sleep(2)
print('I think this is the end of this program, bye')
