wait(3)
Print('Hello')
wait(1)
print('I am a program that is purely made for testing with Python')
wait(2)
print('I hope i am helpfull to you in a good way')
wait(2)
print('And i hope someguy has coded in some stuff in here')
wait(2)
print('I think this is the end of this program, bye')
